### ISSUE TITLE
Maybe a weird question but...

### ISSUE THREAD

**Issue by Markie98** [c6-dev/fose-fps-fix#1]
Why isn't this on Nexus Mods? I haven't even seen it being mentioned there at all. Found it by chance when someone posted it on the FO3 PCGW page. Is it highly WIP or usable already? Anyway thank you very much for it.

**Comment by c6-dev** [comment]
Sure it's usable, but there are many potential caveats when it comes to different setups and modlists, so I didn't feel like putting it on Nexus. I don't know who added it on PCGW.

**Comment by Markie98** [comment]
I see, thanks. Hopefully you can smooth things out with the mod.
